export const RESTAURANT = {
  name: "Fristo Food",
  tagline: "Restaurant snack, pizzas & grillades à Tarrast",
  city: "Inezgane — Agadir",
  district: "Tarrast, Inezgane",
  address: "9F34+W2V, Av. Ermal1, Inezgane 80000",
  phone: "0528834240",
  phoneDisplay: "05 28 83 42 40",
  phoneHref: "tel:+212528834240",
  whatsapp: "+212528834240",
  whatsappHref: "https://wa.me/212528834240?text=Bonjour%20Fristo%20Food,%20je%20souhaite%20passer%20une%20commande.",
  email: null,
  priceRange: "12 DH – 70 DH",
  rating: 4.0,
  reviewCount: 30,
  instagram: "https://www.instagram.com/fristo_food",
  facebook: "https://www.facebook.com/p/Fristo-Food-100088397295539/",
  maps: "https://maps.app.goo.gl/BNBKcsRw7bm9Req98",
  openingHoursDisplay: "7j/7 · 12h00 à 02h00",
} as const;

export const NAV_LINKS = [
  { href: "#accueil", label: "Accueil" },
  { href: "#menu", label: "Menu" },
  { href: "#reservation", label: "Réservation" },
  { href: "#contact", label: "Contact" },
];

export interface ScheduleDay {
  day: string;
  hours: string;
  isOpen: boolean;
}

export const SCHEDULE: ScheduleDay[] = [
  { day: "Lundi", hours: "12h00 – 02h00", isOpen: true },
  { day: "Mardi", hours: "12h00 – 02h00", isOpen: true },
  { day: "Mercredi", hours: "12h00 – 02h00", isOpen: true },
  { day: "Jeudi", hours: "12h00 – 02h00", isOpen: true },
  { day: "Vendredi", hours: "12h00 – 02h00", isOpen: true },
  { day: "Samedi", hours: "12h00 – 02h00", isOpen: true },
  { day: "Dimanche", hours: "12h00 – 02h00", isOpen: true },
];

export interface PizzaPrice {
  small: number;
  large: number;
}

export interface MenuItem {
  id: string;
  name: string;
  category:
    | "plats"
    | "pizza"
    | "tacos"
    | "pasta"
    | "baguto"
    | "panini"
    | "gratin_posstichio"
    | "burger_sandwich"
    | "boss_bowl"
    | "salades"
    | "jus"
    | "desserts";
  subCategory?: string;
  price?: number;
  pizzaPrices?: PizzaPrice;
  description?: string;
  ingredients?: string;
  badge?: string;
  extra?: string;
  popular?: boolean;
}

export const MENU_CATEGORIES = [
  { id: "plats", label: "Plats & Grillades" },
  { id: "pizza", label: "Pizzas & Calzones" },
  { id: "tacos", label: "Tacos" },
  { id: "pasta", label: "Pasta" },
  { id: "baguto", label: "Baguto" },
  { id: "panini", label: "Panini" },
  { id: "gratin_posstichio", label: "Passtichio & Gratins" },
  { id: "burger_sandwich", label: "Burgers & Sandwiches" },
  { id: "boss_bowl", label: "Boss Bowl" },
  { id: "salades", label: "Salades" },
  { id: "jus", label: "Jus & Boissons" },
  { id: "desserts", label: "Desserts & Crêpes" },
];

export const MENU_ITEMS: MenuItem[] = [
  // ================= PLATS & GRILLADES =================
  {
    id: "plat-emince-poulet",
    name: "Plat Émincé Poulet",
    category: "plats",
    price: 40,
    subCategory: "Plats Chauds",
    description: "Émincé de poulet tendre à la crème champignon, servi avec riz pilaf, légumes sautés et frites dorées.",
    popular: true,
  },
  {
    id: "plat-brochettes-poulet",
    name: "Plat Brochettes Poulet (4 brochettes)",
    category: "plats",
    price: 40,
    subCategory: "Grillades au Feu",
    description: "4 brochettes de poulet mariné grillées minute, servies avec riz pilaf, légumes sautés et frites.",
    popular: true,
  },
  {
    id: "plat-brochettes-vh",
    name: "Plat Brochettes Viande Hachée (4 brochettes)",
    category: "plats",
    price: 40,
    subCategory: "Grillades au Feu",
    description: "4 brochettes de kefta pur bœuf assaisonnée maison, riz pilaf, légumes sautés et frites dorées.",
    popular: true,
  },
  {
    id: "plat-escalope",
    name: "Plat Escalope",
    category: "plats",
    price: 35,
    subCategory: "Plats Chauds",
    description: "Escalope dorée à la plancha, servie avec riz pilaf, légumes sautés et frites dorées.",
  },
  {
    id: "plat-merguez",
    name: "Plat Merguez",
    category: "plats",
    price: 35,
    subCategory: "Grillades au Feu",
    description: "Merguez épicées grillées minute, servies avec riz pilaf, légumes sautés et frites.",
  },
  {
    id: "plat-crispy",
    name: "Plat Crispy",
    category: "plats",
    price: 40,
    subCategory: "Plats Chauds",
    description: "Tenders de poulet panés ultra-croustillants, servis avec riz pilaf, légumes sautés et frites.",
    badge: "Crispy",
  },
  {
    id: "plat-mixte",
    name: "Plat Mixte",
    category: "plats",
    price: 40,
    subCategory: "Grillades au Feu",
    description: "Mélange généreux de poulet, viande hachée, escalope et merguez avec accompagnements complets.",
    popular: true,
  },
  {
    id: "plat-pilons",
    name: "Plat de Pilons (3 pilons)",
    category: "plats",
    price: 40,
    subCategory: "Spécialité",
    description: "3 pilons de poulet dorés et croustillants. Accompagnement : pâtes à la crème champignon avec fromage et frites.",
    popular: true,
  },

  // ================= PIZZAS & CALZONES =================
  {
    id: "pizza-margarita",
    name: "Pizza Margarita",
    category: "pizza",
    pizzaPrices: { small: 24, large: 40 },
    subCategory: "Pizza au Four",
    description: "Pâte fraîche maison, sauce tomate mijotée, mozzarella fondante et origan.",
    popular: true,
  },
  {
    id: "pizza-vegetarien",
    name: "Pizza Végétarien",
    category: "pizza",
    pizzaPrices: { small: 25, large: 40 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate, poivrons, champignons, oignons, olives et fromage fondant.",
  },
  {
    id: "pizza-thon",
    name: "Pizza Thon",
    category: "pizza",
    pizzaPrices: { small: 30, large: 50 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate, thon émietté de qualité, fromage fondant et olives noires.",
  },
  {
    id: "pizza-poulet",
    name: "Pizza Poulet",
    category: "pizza",
    pizzaPrices: { small: 30, large: 50 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate, émincé de poulet mariné et fromage fondant doré au four.",
    popular: true,
  },
  {
    id: "pizza-vh",
    name: "Pizza Viande Hachée",
    category: "pizza",
    pizzaPrices: { small: 30, large: 50 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate, kefta pur bœuf assaisonnée maison et fromage fondant.",
    popular: true,
  },
  {
    id: "pizza-fruits-de-mer",
    name: "Pizza Fruits de Mer",
    category: "pizza",
    pizzaPrices: { small: 35, large: 60 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate, crevettes, calamars et fromage fondant doré au four.",
    popular: true,
  },
  {
    id: "pizza-4-fromage",
    name: "Pizza 4 Fromage",
    category: "pizza",
    pizzaPrices: { small: 30, large: 55 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate et généreuse sélection de 4 fromages fondants et savoureux.",
  },
  {
    id: "pizza-dinde-fumee",
    name: "Pizza Dinde Fumée",
    category: "pizza",
    pizzaPrices: { small: 30, large: 55 },
    subCategory: "Pizza au Four",
    description: "Sauce tomate, fines tranches de dinde fumée et fromage fondant.",
  },
  {
    id: "pizza-4-saison",
    name: "Pizza 4 Saison",
    category: "pizza",
    pizzaPrices: { small: 35, large: 62 },
    subCategory: "Pizza au Four",
    description: "Poulet, viande hachée, thon, escalope et fromage fondant sur pâte maison.",
    popular: true,
  },
  {
    id: "pizza-fristo-mixte",
    name: "Pizza Fristo Mixte",
    category: "pizza",
    pizzaPrices: { small: 40, large: 70 },
    subCategory: "Pizza au Four",
    description: "Fruits de mer, dinde fumée, viande hachée pur bœuf, poulet et fromage.",
    badge: "Chef Fristo",
    popular: true,
  },
  // Calzones
  {
    id: "calzone-poulet",
    name: "Calzone Poulet",
    category: "pizza",
    price: 35,
    subCategory: "Calzone Chausson",
    description: "Chausson de pâte à pizza dorée au four, garni de poulet mariné et fromage fondant.",
  },
  {
    id: "calzone-vh",
    name: "Calzone Viande Hachée",
    category: "pizza",
    price: 38,
    subCategory: "Calzone Chausson",
    description: "Chausson garni de kefta pur bœuf assaisonnée maison et fromage fondant.",
  },
  {
    id: "calzone-fruits-de-mer",
    name: "Calzone Fruits de Mer",
    category: "pizza",
    price: 40,
    subCategory: "Calzone Chausson",
    description: "Chausson garni de fruits de mer, sauce savoureuse et fromage fondant.",
  },
  {
    id: "calzone-escalope-nugget",
    name: "Calzone Escalope/Nugget",
    category: "pizza",
    price: 35,
    subCategory: "Calzone Chausson",
    description: "Chausson garni d'escalope dorée ou nuggets croustillants avec fromage.",
  },
  {
    id: "calzone-royal",
    name: "Calzone Royal",
    category: "pizza",
    price: 43,
    subCategory: "Calzone Chausson",
    description: "Poulet, viande hachée pur bœuf, dinde fumée et fromage fondant.",
    popular: true,
  },
  {
    id: "calzone-crispy",
    name: "Calzone Crispy",
    category: "pizza",
    price: 40,
    subCategory: "Calzone Chausson",
    description: "Poulet crispy pané ultra-croustillant et fromage fondant en chausson doré.",
    badge: "Crispy",
  },

  // ================= TACOS =================
  // Tacos Classiques
  {
    id: "tacos-poulet",
    name: "Tacos Poulet",
    category: "tacos",
    price: 30,
    subCategory: "Tacos Classique",
    description: "Galette toastée, émincé de poulet mariné, frites dorées et sauce fromagère onctueuse.",
    popular: true,
  },
  {
    id: "tacos-vh",
    name: "Tacos Viande Hachée",
    category: "tacos",
    price: 32,
    subCategory: "Tacos Classique",
    description: "Kefta pur bœuf assaisonnée, frites dorées et sauce fromagère maison.",
    popular: true,
  },
  {
    id: "tacos-escalope",
    name: "Tacos Escalope",
    category: "tacos",
    price: 30,
    subCategory: "Tacos Classique",
    description: "Tendre escalope dorée à la plancha, frites croustillantes et sauce fromagère.",
  },
  {
    id: "tacos-nugget",
    name: "Tacos Nugget",
    category: "tacos",
    price: 30,
    subCategory: "Tacos Classique",
    description: "Nuggets croustillants, frites dorées et sauce fromagère maison.",
  },
  {
    id: "tacos-mixte",
    name: "Tacos Mixte",
    category: "tacos",
    price: 35,
    subCategory: "Tacos Classique",
    description: "Duo poulet & viande hachée pur bœuf, frites dorées et sauce fromagère.",
    popular: true,
  },
  {
    id: "tacos-crispy",
    name: "Tacos Crispy",
    category: "tacos",
    price: 35,
    subCategory: "Tacos Crispy",
    description: "Poulet crispy pané ultra-croustillant, frites dorées et sauce fromagère maison.",
    badge: "Crispy",
    popular: true,
  },
  // Tacos Gratinés
  {
    id: "tacos-gratine-poulet",
    name: "Tacos Gratiné Poulet",
    category: "tacos",
    price: 33,
    subCategory: "Tacos Gratiné",
    description: "Poulet mariné, frites, gratiné au four sous un généreux nappage de fromage fondant.",
    popular: true,
  },
  {
    id: "tacos-gratine-vh",
    name: "Tacos Gratiné Viande Hachée",
    category: "tacos",
    price: 33,
    subCategory: "Tacos Gratiné",
    description: "Kefta pur bœuf, frites, gratiné au four sous fromage doré.",
    popular: true,
  },
  {
    id: "tacos-gratine-escalope-nugget",
    name: "Tacos Gratiné Escalope/Nugget",
    category: "tacos",
    price: 33,
    subCategory: "Tacos Gratiné",
    description: "Escalope ou nuggets croustillants, frites dorées, gratiné au four sous fromage.",
  },
  {
    id: "tacos-gratine-mixte",
    name: "Tacos Gratiné Mixte",
    category: "tacos",
    price: 37,
    subCategory: "Tacos Gratiné",
    description: "Poulet, viande hachée, dinde fumée, gratiné au four sous fromage fondant.",
    popular: true,
  },
  {
    id: "tacos-gratine-crispy",
    name: "Tacos Gratiné Crispy",
    category: "tacos",
    price: 40,
    subCategory: "Tacos Gratiné",
    description: "Poulet crispy croustillant, frites, gratiné au four sous fromage fondant.",
    badge: "Crispy",
  },
  {
    id: "tacos-gratine-xl",
    name: "Tacos Gratiné XL",
    category: "tacos",
    price: 45,
    subCategory: "Tacos Gratiné XL",
    description: "Format géant XL garni de viandes au choix et frites, gratiné au four sous fromage.",
    popular: true,
  },
  {
    id: "tacos-gratine-xl-mixte",
    name: "Tacos Gratiné XL Mixte",
    category: "tacos",
    price: 50,
    subCategory: "Tacos Gratiné XL",
    description: "Format géant XL mixte toutes viandes, frites, gratiné au four sous fromage fondant.",
    popular: true,
  },
  // Tacos XL Big
  {
    id: "tacos-xl-poulet",
    name: "Tacos XL Big Poulet",
    category: "tacos",
    price: 40,
    subCategory: "Tacos XL Big",
    description: "Double tortilla géante, double dose de poulet mariné, frites et sauce fromagère.",
  },
  {
    id: "tacos-xl-vh",
    name: "Tacos XL Big Viande Hachée",
    category: "tacos",
    price: 42,
    subCategory: "Tacos XL Big",
    description: "Double galette géante, kefta pur bœuf généreuse, frites et sauce fromagère.",
  },
  {
    id: "tacos-xl-escalope",
    name: "Tacos XL Big Escalope",
    category: "tacos",
    price: 40,
    subCategory: "Tacos XL Big",
    description: "Double galette géante, escalope dorée à la plancha, frites et sauce fromagère.",
  },
  {
    id: "tacos-xl-mixte",
    name: "Tacos XL Big Mixte",
    category: "tacos",
    price: 45,
    subCategory: "Tacos XL Big",
    description: "Double galette géante, mélange complet de viandes savoureuses, frites et sauce fromagère.",
    popular: true,
  },
  {
    id: "tacos-xl-crispy",
    name: "Tacos XL Big Crispy",
    category: "tacos",
    price: 45,
    subCategory: "Tacos XL Big",
    description: "Double galette géante, poulet crispy pané maison, frites et sauce fromagère.",
    badge: "Crispy",
  },

  // ================= PASTA =================
  {
    id: "pasta-fermier",
    name: "Pasta Fermier",
    category: "pasta",
    price: 28,
    description: "Sauce blanche onctueuse, pâtes au choix, émincé de poulet, champignons frais et sauce pesto.",
    ingredients: "Au choix : Penne, Spaghetti ou Tagliatelles",
    popular: true,
  },
  {
    id: "pasta-bolognese",
    name: "Pasta Bolognese",
    category: "pasta",
    price: 30,
    description: "Sauce tomate parfumée maison, pâtes au choix, viande pur bœuf, champignons et sauce pesto.",
    ingredients: "Au choix : Penne, Spaghetti ou Tagliatelles",
    popular: true,
  },
  {
    id: "pasta-carbonara",
    name: "Pasta Carbonara",
    category: "pasta",
    price: 27,
    description: "Sauce blanche crémeuse, pâtes au choix, fromage fondant, charcuterie savoureuse, champignons et pesto.",
    ingredients: "Au choix : Penne, Spaghetti ou Tagliatelles",
  },
  {
    id: "pasta-pecheur",
    name: "Pasta Pêcheur",
    category: "pasta",
    price: 35,
    description: "Sauce blanche, pâtes au choix, fromage, sélection de fruits de mer, champignons et sauce pesto.",
    ingredients: "Au choix : Penne, Spaghetti ou Tagliatelles",
    popular: true,
  },
  {
    id: "pasta-poulet-truffe",
    name: "Pasta Poulet à la Truffe",
    category: "pasta",
    price: 30,
    description: "Pâtes au choix, poulet mariné, champignons, sauce blanche crémeuse à la crème champignon arôme truffe.",
    ingredients: "Au choix : Penne, Spaghetti ou Tagliatelles",
    popular: true,
  },

  // ================= BAGUTO =================
  {
    id: "baguto-poulet",
    name: "Baguto Poulet",
    category: "baguto",
    price: 30,
    description: "Baguette croustillante toastée à la plancha, émincé de poulet mariné et fromage fondant.",
    extra: "Option Frites : + 5 DH",
    popular: true,
  },
  {
    id: "baguto-vh",
    name: "Baguto Viande Hachée",
    category: "baguto",
    price: 32,
    description: "Baguette toastée minute, kefta pur bœuf assaisonnée et fromage fondu crémeux.",
    extra: "Option Frites : + 5 DH",
    popular: true,
  },
  {
    id: "baguto-escalope",
    name: "Baguto Escalope",
    category: "baguto",
    price: 30,
    description: "Baguette toastée minute, escalope dorée à la plancha et fromage fondant.",
    extra: "Option Frites : + 5 DH",
  },
  {
    id: "baguto-mixte",
    name: "Baguto Mixte",
    category: "baguto",
    price: 35,
    description: "Baguette toastée garnie de dinde, viande hachée, escalope et fromage fondant.",
    extra: "Option Frites : + 5 DH",
    badge: "Spécialité Fristo",
    popular: true,
  },
  {
    id: "baguto-crispy",
    name: "Baguto Crispy",
    category: "baguto",
    price: 40,
    description: "Baguette toastée, tenders de poulet crispy ultra-croustillants, sauce et fromage fondant.",
    extra: "Option Frites : + 5 DH",
    badge: "Crispy",
    popular: true,
  },

  // ================= PANINI =================
  {
    id: "panini-poulet",
    name: "Panini Poulet",
    category: "panini",
    price: 18,
    description: "Pain croustillant grillé minute garni de poulet mariné et fromage fondant.",
    popular: true,
  },
  {
    id: "panini-vh",
    name: "Panini Viande Hachée",
    category: "panini",
    price: 20,
    description: "Kefta savoureuse pur bœuf grillée à la plancha et fromage fondu crémeux.",
    popular: true,
  },
  {
    id: "panini-escalope",
    name: "Panini Escalope",
    category: "panini",
    price: 18,
    description: "Tendre escalope dorée à la plancha avec fromage crémeux fondu.",
  },
  {
    id: "panini-nugget",
    name: "Panini Nugget",
    category: "panini",
    price: 18,
    description: "Nuggets croustillants et fromage fondant toastés minute à la commande.",
  },
  {
    id: "panini-mixte",
    name: "Panini Mixte",
    category: "panini",
    price: 20,
    description: "Mélange savoureux de viandes sélectionnées et fromage fondu.",
    popular: true,
  },
  {
    id: "panini-thon",
    name: "Panini Thon",
    category: "panini",
    price: 18,
    description: "Thon fondant et fromage toastés minute.",
  },

  // ================= PASSTICHIO & GRATINS =================
  // Passtichio (Base Frites)
  {
    id: "passtichio-poulet",
    name: "Passtichio Poulet",
    category: "gratin_posstichio",
    price: 25,
    subCategory: "Passtichio (Base Frites)",
    description: "Lit de frites dorées, poulet mariné, nappage généreux de fromage fondant gratiné au four.",
    popular: true,
  },
  {
    id: "passtichio-vh",
    name: "Passtichio Viande Hachée",
    category: "gratin_posstichio",
    price: 28,
    subCategory: "Passtichio (Base Frites)",
    description: "Lit de frites dorées, kefta pur bœuf assaisonnée et fromage fondant gratiné.",
    popular: true,
  },
  {
    id: "passtichio-fruits-de-mer",
    name: "Passtichio Fruits de Mer",
    category: "gratin_posstichio",
    price: 35,
    subCategory: "Passtichio (Base Frites)",
    description: "Lit de frites dorées, fruits de mer, sauce crémeuse et fromage fondant gratiné.",
  },
  {
    id: "passtichio-mixte",
    name: "Passtichio Mixte",
    category: "gratin_posstichio",
    price: 30,
    subCategory: "Passtichio (Base Frites)",
    description: "Lit de frites dorées, poulet, viande hachée, dinde fumée et fromage fondant.",
    popular: true,
  },
  // Gratins au Four (Base Purée ou Pâtes)
  {
    id: "gratin-poulet",
    name: "Gratin Poulet",
    category: "gratin_posstichio",
    price: 25,
    subCategory: "Gratin au Four",
    description: "Au choix base Purée maison ou Pâtes, émincé de poulet mariné et fromage gratiné au four.",
  },
  {
    id: "gratin-vh",
    name: "Gratin Viande Hachée",
    category: "gratin_posstichio",
    price: 28,
    subCategory: "Gratin au Four",
    description: "Au choix base Purée ou Pâtes, kefta pur bœuf, sauce onctueuse et fromage gratiné.",
  },
  {
    id: "gratin-fruits-de-mer",
    name: "Gratin Fruits de Mer",
    category: "gratin_posstichio",
    price: 35,
    subCategory: "Gratin au Four",
    description: "Au choix base Purée ou Pâtes, fruits de mer, sauce crémeuse et fromage gratiné.",
  },
  {
    id: "gratin-mixte",
    name: "Gratin Mixte",
    category: "gratin_posstichio",
    price: 30,
    subCategory: "Gratin au Four",
    description: "Au choix base Purée ou Pâtes, poulet, viande hachée, dinde fumée et fromage gratiné.",
    popular: true,
  },

  // ================= BURGERS & SANDWICHES & CHIKA =================
  // Burgers
  {
    id: "burger-cheese",
    name: "Cheese Burger",
    category: "burger_sandwich",
    price: 22,
    subCategory: "Burger Gourmet",
    description: "Pain brioché artisanal, steak pur bœuf, cheddar fondant, crudités fraîches et sauce secrète.",
  },
  {
    id: "burger-chicken",
    name: "Chicken Burger",
    category: "burger_sandwich",
    price: 20,
    subCategory: "Burger Gourmet",
    description: "Filet de poulet croustillant, cheddar fondu, salade fraîche et sauce burger.",
  },
  {
    id: "burger-double-cheese",
    name: "Double Cheese Burger",
    category: "burger_sandwich",
    price: 30,
    subCategory: "Burger Gourmet",
    description: "Double steak pur bœuf, double tranche de cheddar fondant, crudités et sauce.",
    popular: true,
  },
  {
    id: "burger-double-chicken",
    name: "Double Chicken Burger",
    category: "burger_sandwich",
    price: 26,
    subCategory: "Burger Gourmet",
    description: "Double filet de poulet, double cheddar fondu et crudités croquantes.",
  },
  {
    id: "burger-fristo",
    name: "Fristo Burger",
    category: "burger_sandwich",
    price: 35,
    subCategory: "Burger Gourmet",
    description: "Steak pur bœuf, filet de poulet, cheddar, dinde fumée et œuf au plat avec frites dorées.",
    badge: "Spécialité Fristo",
    popular: true,
  },
  // Sandwiches
  {
    id: "sandwich-poulet",
    name: "Sandwich Poulet",
    category: "burger_sandwich",
    price: 18,
    subCategory: "Sandwich",
    description: "Pain croustillant, poulet mariné cuit minute, crudités du jour et sauce au choix.",
  },
  {
    id: "sandwich-vh",
    name: "Sandwich Viande Hachée",
    category: "burger_sandwich",
    price: 20,
    subCategory: "Sandwich",
    description: "Kefta pur bœuf assaisonnée maison, crudités fraîches et sauce au choix.",
  },
  {
    id: "sandwich-escalope-nugget",
    name: "Sandwich Escalope/Nugget",
    category: "burger_sandwich",
    price: 18,
    subCategory: "Sandwich",
    description: "Escalope dorée ou nuggets croustillants avec crudités fraîches.",
  },
  {
    id: "sandwich-mixte",
    name: "Sandwich Mixte",
    category: "burger_sandwich",
    price: 20,
    subCategory: "Sandwich",
    description: "Mélange généreux poulet et viande hachée pur bœuf, crudités et sauce.",
  },
  {
    id: "sandwich-thon",
    name: "Sandwich Thon",
    category: "burger_sandwich",
    price: 18,
    subCategory: "Sandwich",
    description: "Thon savoureux, crudités fraîches et sauce au choix.",
  },
  // Chika
  {
    id: "chika-poulet",
    name: "Chika Poulet",
    category: "burger_sandwich",
    price: 23,
    subCategory: "Chika",
    description: "Pain spécial toasté garni de poulet mariné et sauce au choix.",
  },
  {
    id: "chika-vh",
    name: "Chika Viande Hachée",
    category: "burger_sandwich",
    price: 25,
    subCategory: "Chika",
    description: "Pain toasté garni de kefta pur bœuf grillée et sauce.",
  },
  {
    id: "chika-escalope-nugget",
    name: "Chika Escalope/Nugget",
    category: "burger_sandwich",
    price: 25,
    subCategory: "Chika",
    description: "Escalope dorée ou nuggets croustillants en pain toasté.",
  },
  {
    id: "chika-extra",
    name: "Chika Extra",
    category: "burger_sandwich",
    price: 25,
    subCategory: "Chika",
    description: "Dinde, escalope dorée et jambon de dinde avec fromage.",
  },
  {
    id: "chika-radical",
    name: "Chika Radical",
    category: "burger_sandwich",
    price: 27,
    subCategory: "Chika",
    description: "Viande hachée pur bœuf, escalope dorée et œuf au plat.",
    popular: true,
  },
  {
    id: "chika-mixte",
    name: "Chika Mixte",
    category: "burger_sandwich",
    price: 28,
    subCategory: "Chika",
    description: "Mélange savoureux de viandes sélectionnées en pain toasté.",
  },
  {
    id: "chika-crispy",
    name: "Chika Crispy",
    category: "burger_sandwich",
    price: 28,
    subCategory: "Chika",
    description: "Poulet crispy pané ultra-croustillant en pain toasté.",
    badge: "Crispy",
  },

  // ================= BOSS BOWL =================
  {
    id: "boss-bowl-poulet",
    name: "Boss Bowl Poulet",
    category: "boss_bowl",
    price: 30,
    description: "Au choix base Riz pilaf ou Pâtes sauce champignon, poulet mariné, fromage, sauce pesto, mayonnaise.",
    popular: true,
  },
  {
    id: "boss-bowl-vh",
    name: "Boss Bowl Viande Hachée",
    category: "boss_bowl",
    price: 30,
    description: "Au choix base Riz pilaf ou Pâtes sauce champignon, viande hachée pur bœuf, fromage, sauce pesto, mayonnaise.",
  },
  {
    id: "boss-bowl-mixte",
    name: "Boss Bowl Mixte",
    category: "boss_bowl",
    price: 35,
    description: "Au choix base Riz pilaf ou Pâtes sauce champignon, poulet, viande hachée, merguez, jambon dinde, fromage, sauce pesto, mayonnaise.",
    popular: true,
  },
  {
    id: "boss-bowl-crispy",
    name: "Boss Bowl Crispy",
    category: "boss_bowl",
    price: 40,
    description: "Au choix base Riz pilaf ou Pâtes sauce champignon, tenders de poulet crispy croustillants, fromage, sauce pesto, mayonnaise.",
    badge: "Crispy",
    popular: true,
  },

  // ================= SALADES =================
  {
    id: "salade-nicoise",
    name: "Salade Niçoise",
    category: "salades",
    price: 20,
    description: "Concombre, carottes râpées, haricots verts, pommes de terre, betteraves, tomates, salade verte, thon, maïs, mayonnaise, sauce pesto.",
  },
  {
    id: "salade-italienne",
    name: "Salade Italienne",
    category: "salades",
    price: 25,
    description: "Riz, pâtes, thon, jambon de dinde, maïs, œuf, olives vertes, tomates cerises, fromage, mayonnaise, sauce pesto.",
  },
  {
    id: "salade-poulet-italienne",
    name: "Salade Poulet Italienne",
    category: "salades",
    price: 30,
    description: "Pâtes, riz, thon, salade verte, maïs, œuf, olives vertes, émincé de poulet mariné, mayonnaise, sauce pesto.",
    popular: true,
  },
  {
    id: "salade-pecheur",
    name: "Salade Pêcheur",
    category: "salades",
    price: 35,
    description: "Base salade verte, crevettes, seiche/sépia, tomates cerises, avocat, surimi, fromage, mayonnaise, sauce pesto.",
    popular: true,
  },
  {
    id: "salade-fristo",
    name: "Salade Fristo",
    category: "salades",
    price: 32,
    description: "Pâtes, riz, thon, salade verte, jambon de dinde, escalope, maïs, raisins secs, olives vertes, pommes de terre, pomme, banane, tomates cerises, fromage, mayonnaise, sauce pesto.",
    badge: "Chef Fristo",
    popular: true,
  },
  {
    id: "salade-cesar",
    name: "Salade César",
    category: "salades",
    price: 25,
    description: "Base salade verte croquante, tomates cerises, poulet grillé, croûtons dorés, sauce pesto et mayonnaise.",
    popular: true,
  },
  {
    id: "salade-cocktail",
    name: "Salade Cocktail",
    category: "salades",
    price: 35,
    description: "Salade verte, émincé de poulet, fruits frais, fruits secs, tomates cerises, fromage rouge, sauce spéciale maison.",
  },
  {
    id: "salade-terre-mer",
    name: "Salade Terre et Mer",
    category: "salades",
    price: 30,
    description: "Riz, pâtes, pommes de terre, thon, tomates, olives, maïs, surimi, crevettes, poivrons, fromage, sauce pesto, mayonnaise et citron.",
  },
  {
    id: "supplement-extra-poulet",
    name: "Supplément Extra Poulet",
    category: "salades",
    price: 6,
    description: "Portion supplémentaire de poulet mariné grillé minute pour accompagner votre salade.",
  },

  // ================= JUS & BOISSONS =================
  {
    id: "jus-orange",
    name: "Jus d'Orange Frais",
    category: "jus",
    price: 13,
    description: "Oranges fraîches pressées minute à la commande, 100% pur jus naturel sans sucre ajouté.",
    popular: true,
  },
  {
    id: "jus-citron",
    name: "Jus de Citron",
    category: "jus",
    price: 12,
    description: "Citronnade tonifiante, fraîche et désaltérante.",
  },
  {
    id: "jus-banane",
    name: "Jus de Banane",
    category: "jus",
    price: 12,
    description: "Bananes fraîches mixées avec du lait entier onctueux.",
  },
  {
    id: "jus-pomme",
    name: "Jus de Pomme",
    category: "jus",
    price: 12,
    description: "Pommes fraîches pressées minute, doux et rafraîchissant.",
  },
  {
    id: "jus-mangue",
    name: "Jus de Mangue",
    category: "jus",
    price: 17,
    description: "Mangue veloutée et savoureuse pressée minute.",
    popular: true,
  },
  {
    id: "jus-ananas",
    name: "Jus d'Ananas",
    category: "jus",
    price: 16,
    description: "Ananas frais pressé minute, sucré et exotique.",
  },
  {
    id: "jus-avocat",
    name: "Jus d'Avocat",
    category: "jus",
    price: 15,
    description: "Avocat crémeux mixé au lait avec une touche de douceur.",
  },
  {
    id: "jus-avocat-fruits-secs",
    name: "Jus d'Avocat Fruits Secs",
    category: "jus",
    price: 20,
    description: "Avocat royal crémeux enrichi de fruits secs, amandes et raisins secs.",
    badge: "Royal",
    popular: true,
  },
  {
    id: "jus-betterave",
    name: "Jus de Betterave",
    category: "jus",
    price: 15,
    description: "Betterave fraîche détox, saine et vitaminée.",
  },
  {
    id: "jus-panache",
    name: "Jus Panaché",
    category: "jus",
    price: 16,
    description: "Cocktail vitaminé aux fruits frais de saison mixés à la minute.",
    popular: true,
  },
  {
    id: "boisson-soda",
    name: "Soda (Canette)",
    category: "jus",
    price: 6,
    description: "Boisson gazeuse fraîche au choix (Coca-Cola, Fanta, Sprite, Hawaï, Pom's...).",
  },
  {
    id: "boisson-eau",
    name: "Eau Minérale 33cl",
    category: "jus",
    price: 3,
    description: "Bouteille d'eau minérale naturelle bien fraîche.",
  },

  // ================= DESSERTS & CRÊPES =================
  {
    id: "tiramisu-chocolat",
    name: "Tiramisu Chocolat",
    category: "desserts",
    price: 12,
    subCategory: "Tiramisu Maison",
    description: "Crème onctueuse au mascarpone, biscuits imbibés et cacao fin.",
  },
  {
    id: "tiramisu-oreo",
    name: "Tiramisu Oreo",
    category: "desserts",
    price: 12,
    subCategory: "Tiramisu Maison",
    description: "Tiramisu crémeux aux éclats croustillants de biscuits Oreo.",
    popular: true,
  },
  {
    id: "tiramisu-caramel",
    name: "Tiramisu Caramel",
    category: "desserts",
    price: 12,
    subCategory: "Tiramisu Maison",
    description: "Tiramisu fondant avec coulis de caramel gourmand.",
  },
  {
    id: "tiramisu-fraise",
    name: "Tiramisu Fraise",
    category: "desserts",
    price: 12,
    subCategory: "Tiramisu Maison",
    description: "Tiramisu frais et léger au coulis de fraises.",
  },
  {
    id: "crepe-nutella",
    name: "Crêpe Nutella",
    category: "desserts",
    price: 22,
    subCategory: "Crêpe",
    description: "Crêpe dorée minute généreusement nappée de Nutella fondant.",
    popular: true,
  },
  {
    id: "crepe-banane",
    name: "Crêpe Banane",
    category: "desserts",
    price: 24,
    subCategory: "Crêpe",
    description: "Crêpe dorée, rondelles de bananes fraîches et chocolat fondant.",
  },
  {
    id: "crepe-royale",
    name: "Crêpe Royale",
    category: "desserts",
    price: 30,
    subCategory: "Crêpe",
    description: "Crêpe gourmande avec Nutella, bananes fraîches et fruits secs.",
    badge: "Royale",
    popular: true,
  },
];


export interface ReviewItem {
  name: string;
  city: string;
  rating: number;
  date: string;
  comment: string;
}

export const REVIEWS: ReviewItem[] = [
  {
    name: "Youssef El Mansouri",
    city: "Inezgane",
    rating: 5,
    date: "Il y a 2 semaines",
    comment: "Le meilleur snack de Tarrast sans hésitation ! Les sandwichs kefta sont préparés minute sur la plancha avec des produits très frais. L'accueil est chaleureux et le service est ultra rapide.",
  },
  {
    name: "Fatima-Zahra B.",
    city: "Agadir",
    rating: 5,
    date: "Il y a 1 mois",
    comment: "Une adresse fidèle depuis des mois. Les tacos sont généreusement garnis avec une vraie bonne sauce fromagère qui fait la différence. Rapport qualité-prix imbattable dans la zone d'Inezgane.",
  },
  {
    name: "Mehdi Amrani",
    city: "Dcheira",
    rating: 5,
    date: "Il y a 3 semaines",
    comment: "Excellente pause déjeuner. Le burger Fristo est savoureux avec du pain bien moelleux et les frites arrivent croustillantes. Endroit très propre et équipe souriante.",
  },
  {
    name: "Amina Tazi",
    city: "Aït Melloul",
    rating: 5,
    date: "Il y a 2 mois",
    comment: "Tout est préparé sous vos yeux en direct. Les portions sont copieuses et les viandes sont parfaitement marinées. On y revient à chaque passage sur l'avenue Ermal1 !",
  },
];

export interface FAQItem {
  question: string;
  answer: string;
}

export const FAQS: FAQItem[] = [
  {
    question: "Toutes les viandes sont-elles garanties 100% Halal ?",
    answer: "Oui, absolument. Toutes nos viandes (bœuf, kefta, poulet mariné, dinde) sont certifiées 100% halal, sélectionnées auprès de bouchers locaux de confiance et préparées chaque matin pour garantir une fraîcheur irréprochable.",
  },
  {
    question: "Quels sont vos horaires d'ouverture ?",
    answer: "Nous sommes ouverts 7 jours sur 7, en continu de 12h00 à 02h00 du matin, pour vos déjeuners, dîners et commandes nocturnes.",
  },
  {
    question: "Proposez-vous le service sur place et à emporter ?",
    answer: "Oui, nous vous accueillons dans notre salle conviviale sur place à Tarrast, ou préparons votre commande à emporter. Vous pouvez également nous appeler 15 minutes à l'avance pour un retrait express sans attente.",
  },
  {
    question: "Comment réserver une table ou commander à l'avance ?",
    answer: "Vous pouvez réserver directement via notre formulaire en ligne sur le site ou en nous appelant au 05 28 83 42 40. Nous vous confirmons votre table ou lançons la cuisson pour votre arrivée.",
  },
];
